apiVersion: apps/v1
kind: Deployment
metadata:
  name: themis-executor
  namespace: themis-executor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: themis-executor
  template:
    metadata:
      labels:
        app: themis-executor
    spec:
      serviceAccountName: themis-executor
      containers:
        - name: themis
          image: k8loud/themis-executor:0.0.4.4
          imagePullPolicy: "Always"
          env:
            - name: DROOLS_RULES_PATH
              value: /rules/rules.drl
            - name: DROOLS_QUERY_AND_PROCESS_FIXED_RATE_SECONDS
              value: "10"
            - name: HEPHAESTUS_URL
              value: http://hephaestus-gui.hephaestus.svc.cluster.local:8080
            - name: HEPHAESTUS_SELECTED_ENDPOINT
              value: /hephaestus/metrics/selected
            - name: KUBERNETES_MASTER
              valueFrom:
                secretKeyRef:
                  name: themis-secrets-k8s
                  key: KUBERNETES_MASTER
            - name: KUBERNETES_CA_CERT_DATA
              valueFrom:
                secretKeyRef:
                  name: themis-secrets-k8s
                  key: KUBERNETES_CA_CERT_DATA
            - name: KUBERNETES_CLIENT_CERT_DATA
              valueFrom:
                secretKeyRef:
                  name: themis-secrets-k8s
                  key: KUBERNETES_CLIENT_CERT_DATA
            - name: KUBERNETES_CLIENT_KEY_DATA
              valueFrom:
                secretKeyRef:
                  name: themis-secrets-k8s
                  key: KUBERNETES_CLIENT_KEY_DATA
            - name: DATA_STORAGE_ROOT_PATH
              value: /tmp
            - name: DATA_STORAGE_REMOVAL_PERMITTED
              value: "true"
            - name: MAIL_HOST
              value: smtp-mail.outlook.com
            - name: MAIL_PORT
              value: "587"
            - name: MAIL_ADDRESS
              value: weedesigners@hotmail.com
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: themis-secrets-mail
                  key: MAIL_PASSWORD
            - name: OPENSTACK_USERNAME
              valueFrom:
                secretKeyRef:
                  name: themis-secrets-openstack
                  key: OPENSTACK_USERNAME
            - name: OPENSTACK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: themis-secrets-openstack
                  key: OPENSTACK_PASSWORD
            - name: OPENSTACK_ENDPOINT
              value: https://api.cloud.cyfronet.pl:5000/v3
            - name: OPENSTACK_DOMAIN_NAME
              value: Default
            - name: OPENSTACK_DOMAIN_I_D
              value: default
            - name: OPENSTACK_PROJECT_I_D
              value: 795986d75bae4609aec541f073213917
            - name: OPENSTACK_OPENSTACK_AUTH
              value: PROJECT_SCOPED
            - name: SERVICE_ENABLED_HEPHAESTUS
              value: "true"
            - name: SERVICE_ENABLED_DROOLS
              value: "false"
          resources:
            limits:
              cpu: 900m
              memory: 900Mi
            requests:
              cpu: 900m
              memory: 900Mi
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: rules-volume
              mountPath: /rules
      volumes:
        - name: rules-volume
          configMap:
            name: rules
