apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes
  namespace: hermes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hermes
  template:
    metadata:
      labels:
        app: hermes
    spec:
      containers:
        - name: hermes
          image: weedesigners/hermes:latest
          env:
            - name: HERMES_ADDRESS
              value: "0.0.0.0"
            - name: HERMES_PORT
              value: "8080"
            - name: ZEUS_URL
              value: http://zeuspol.zeuspol:8080

          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 900m
              memory: 900Mi
            requests:
              cpu: 900m
              memory: 900Mi
