---
name: Multibranch Java CI with Maven

on:
  push:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Super-linter
      uses: super-linter/super-linter/slim@v7.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_JAVA: true
        VALIDATE_BASH: true
        VALIDATE_YAML_PRETTIER: true
        VALIDATE_XML: true
        VALIDATE_TERRAFORM_TFLINT: true
        VALIDATE_TERRAFORM_TERRASCAN: true
        VALIDATE_TERRAFORM_FMT: true
        VALIDATE_MARKDOWN: true
        VALIDATE_KUBERNETES_KUBECONFORM: true
        VALIDATE_GITHUB_ACTIONS: true
        VALIDATE_GITLEAKS: true
        VALIDATE_DOCKERFILE_HADOLINT: true

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml


    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#    - name: Update dependency graph
#      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
