---
name: CI

on:
  pull_request:
    types:
      - opened
      - closed
    branches: [main]

jobs:
  ci:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-linter
        continue-on-error: true
        uses: super-linter/super-linter/slim@v7.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JAVA: true

      - name: Maven build
        if: github.event.pull_request.merged == true
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Maven test and build
        if: github.event.pull_request.merged == true
        run: mvn -B clean package --file pom.xml

      - name: Log in to Docker Hub
        if: github.event.pull_request.merged == true
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        if: github.event.pull_request.merged == true
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: weedesigners/zeuspol

      - name: Build and push Docker image
        if: github.event.pull_request.merged == true
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
